# Generated by Django 5.2.16 on 2026-07-14 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MigrationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_system", models.CharField(max_length=255)),
                (
                    "extraction_mode",
                    models.CharField(
                        choices=[
                            ("search", "Paged search"),
                            ("bulk_export", "Bulk export"),
                        ],
                        default="search",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("cutoff_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_transaction_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("checkpoint", models.JSONField(blank=True, default=dict)),
                ("request_count", models.PositiveBigIntegerField(default=0)),
                ("retry_count", models.PositiveBigIntegerField(default=0)),
                ("discovered_count", models.PositiveBigIntegerField(default=0)),
                ("parsed_count", models.PositiveBigIntegerField(default=0)),
                ("accepted_count", models.PositiveBigIntegerField(default=0)),
                ("rejected_count", models.PositiveBigIntegerField(default=0)),
                ("inserted_count", models.PositiveBigIntegerField(default=0)),
                ("updated_count", models.PositiveBigIntegerField(default=0)),
                ("unchanged_count", models.PositiveBigIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_system", models.CharField(max_length=255)),
                ("fhir_id", models.CharField(max_length=255)),
                ("source_version_id", models.CharField(blank=True, max_length=255)),
                ("source_last_updated", models.DateTimeField(blank=True, null=True)),
                ("names", models.JSONField(blank=True, default=list)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("birth_date", models.CharField(blank=True, max_length=10, null=True)),
                ("active", models.BooleanField(blank=True, null=True)),
                ("identifiers", models.JSONField(blank=True, default=list)),
                ("telecom", models.JSONField(blank=True, default=list)),
                ("addresses", models.JSONField(blank=True, default=list)),
                ("communications", models.JSONField(blank=True, default=list)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_system", "fhir_id"),
                        name="uniq_patient_source_fhir_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_system", models.CharField(max_length=255)),
                ("fhir_id", models.CharField(max_length=255)),
                ("source_version_id", models.CharField(blank=True, max_length=255)),
                ("source_last_updated", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("code_codings", models.JSONField(blank=True, default=list)),
                ("code_text", models.TextField(blank=True)),
                ("display_label", models.CharField(blank=True, max_length=255)),
                ("value_type", models.CharField(blank=True, max_length=64)),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=38, null=True
                    ),
                ),
                ("value_text", models.TextField(blank=True)),
                ("value_unit", models.CharField(blank=True, max_length=255)),
                ("data_absent_reason", models.JSONField(blank=True, null=True)),
                ("components", models.JSONField(blank=True, default=list)),
                ("reference_ranges", models.JSONField(blank=True, default=list)),
                ("effective_type", models.CharField(blank=True, max_length=64)),
                ("effective", models.JSONField(blank=True, null=True)),
                ("effective_at", models.DateTimeField(blank=True, null=True)),
                ("issued", models.DateTimeField(blank=True, null=True)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="fhir_migration.patient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["patient", "effective_at"],
                        name="obs_patient_effective_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_system", "fhir_id"),
                        name="uniq_observation_source_fhir_id",
                    )
                ],
            },
        ),
    ]
